### PR TITLE
fix NPE in headless environment

### PR DESCRIPTION
**Pull request by don-vip**
Dialogs are not created in JOSM unit tests because of headless environment

### CODE REVIEW

**Comment by don-vip** [comment]
thanks! :) can you please make a release soon?

**Comment by beataj-telenav** [comment]
Hello Vincent,
We will create a new release this week. Currently I’m fixing some other bugs.

Thanks for contributing ☺

**Comment by don-vip** [comment]
Great :) I was also planning to do another PR like those ones, would you accept it? Or maybe is it already on your radar?
https://github.com/Telenav/traffic-flow-direction/pull/4
https://github.com/Telenav/scoutsigns/pull/3
https://github.com/Telenav/missingroads/pull/4

**Comment by beataj-telenav** [comment]
Hello,

This is already in our list.

Thanks ☺

**Comment by don-vip** [comment]
Hi Beata,
can we have some news on the upcoming release? :)

**Comment by beataj-telenav** [comment]
Hello Vincent,

We had a release on Friday that includes also your fix from GiitHub.

Best regards,
Bea.

**Comment by don-vip** [comment]
ok right there's another issue, I believed it was the same one.
I'll come with a new PR.

**Pull request merged**
