### PR TITLE
fix NPE again

### PR DESCRIPTION
**Pull request by don-vip**
I already fixed this in https://github.com/Telenav/improve-osm-plugin/commit/64fa02d556e6839cc4bafbd3e179058bc7521d17

But the commit has been reverted, why? Now the error happens again, see https://josm.openstreetmap.de/ticket/12482

### CODE REVIEW

**Comment by stoecker** [comment]
Your other fix was also reverted.

**Comment by beataj-telenav** [comment]
With the next release this will be solved.

**Comment by beataj-telenav** [comment]
Hello Vincent,

The fix might have been removed accidentally when we synchronized the GitHub ImproveOsm code with our internal development svn.
In our latest version that will be released soon (this week/early next week) also this fix is included.

Best regards,

Bea.

**Comment by stoecker** [comment]
This is still missing: https://github.com/Telenav/improve-osm-plugin/commit/a57f6f647fa05e48d1bf902fbf3ad9651d31098b

**Comment by beataj-telenav** [comment]
This fix is contained in our latest development version which will be released soon. Also the GitHub source code will be updated soon.

**Comment by beataj-telenav** [comment]
That fix was moved up to the mapFrameInitialized() method.

**Pull request merged**
